### ISSUE TITLE
Atualizações no cadastro de Arquivamento de Caixas

### ISSUE THREAD

**Issue by baraky** [fga-eps-mds/2021-2-SysArq-Doc#106]
## Descrição

Há algumas mudanças (e adições) que precisam ser feitas no cadastro de Arquivamento de Caixas.

## Critérios de aceitação 

- [x] Renomear o campo Caixa de Origem para Caixa(s) para Arquivamento
- [ ] Implementar possibilidade de adicionar mais de uma caixa
No cadastro da caixa:
     - [x] Renomear campo Assunto para Nome do Documento (vinculado ao campo obrigatório)
     - [x] Renomear o campo Data para Data do Documento
     - [ ] Campo Data do Documento com apenas mês e ano (sendo apenas ano obrigatório)
     OBS: pode seguir o modelo da aba do Tipo do Documento para caixa, 
     - [x] Adicionar campo Observação em cada caixa cadastrada
     - [x] Adicionar o campo Localidade do Arquivo, seguido de Estante e Prateleira para cada Caixa
- [x] Excluir campo Tipo de Documento
- [x] Excluir campo Sigla da Caixa, Ano da Caixa e Número da Caixa
- [x] Excluir campos Estante e Prateleira (vão estar dentro do cadastro de caixa)
- [x] Limpar campo Data do Recebimento (deixar em branco, não estipular data)

**Comment by dartmol203** [comment]
devo retirar a opção de observação e deixar apenas a interna das caixas?

**Comment by dartmol203** [comment]
Boa noite, seria possível alguém me auxiliar com essa issue, não estou conseguindo avançar nela de forma alguma, qualquer ajuda seria bem vinda
