### ISSUE TITLE
Informar quando o documento atinge a temporalidade

### ISSUE THREAD

**Issue by baraky** [fga-eps-mds/2021-2-SysArq-Doc#37]
## Descrição

Informar na listagem quando a temporalidade de um documento é atingida.

## Critérios de aceitação

- [ ] Informar quando o documento atingir a temporalidade definida

## Observações

A solução seria algo como uma marcação na lista quando o documento atinge a temporalidade. A ideia é que o usuário tome uma decisão do que fazer na situação.

**Comment by paulomacieltorresfilho** [comment]
Como atualmente a temporalidade é marcada por anos (inclusive no SysArq-Archives), estamos tendo dúvidas a respeito de quando marcar o fim da temporalidade, no ano ou no ano seguinte:? Ex: um documento com data em 2022 tem temporalidade de 10 anos, devemos informar que atingiu a temporalidade em 2022 ou em 2023?

**Comment by baraky** [comment]
> Como atualmente a temporalidade é marcada por anos (inclusive no SysArq-Archives), estamos tendo dúvidas a respeito de quando marcar o fim da temporalidade, no ano ou no ano seguinte? Ex: um documento com data em 2022 tem temporalidade de 10 anos, devemos informar que atingiu a temporalidade em 2022 ou em 2023?

Se um documento foi criado em 02/05/2012 com temporalidade de 10 anos, em 02/05/2022 deve informar que atingiu a temporalidade.

É basicamente adicionar o número de anos da temporalidade ao ano que ele foi criado, se o dia atual foi >=, informa.

**Comment by paulomacieltorresfilho** [comment]
> > Como atualmente a temporalidade é marcada por anos (inclusive no SysArq-Archives), estamos tendo dúvidas a respeito de quando marcar o fim da temporalidade, no ano ou no ano seguinte? Ex: um documento com data em 2022 tem temporalidade de 10 anos, devemos informar que atingiu a temporalidade em 2022 ou em 2023?
> 
> Se um documento foi criado em 02/05/2012 com temporalidade de 10 anos, em 02/05/2022 deve informar que atingiu a temporalidade.
> 
> É basicamente adicionar o número de anos da temporalidade ao ano que ele foi criado, se o dia atual for maior ou igual, informa.

É porque acho que o valor próprio da temporalidade não é informado nos dados da requisição, mas amanhã vou conferir. Hoje quando dei uma olhada só vi que uma das informações era o ano que atingia a temporalidade, como `temporality_date` ou `temporality_year`.

**Comment by paulomacieltorresfilho** [comment]
Acabei de conferir aqui, cada documento armazena só o ano da temporalidade. `temporality_date: 2032`

**Comment by paulomacieltorresfilho** [comment]
Acho que descobri uma forma de fazer, vou atualizando qualquer coisa.
