### ISSUE TITLE
Tela de gerenciamento de usuários

### ISSUE THREAD

**Issue by baraky** [fga-eps-mds/2021-2-SysArq-Doc#54]
## Descrição
Implementar tela de gerenciamento de usuários cadastrados no sistema. Nessa tela, deve contar a lista de usuários cadastrados com as opções de deletar e editar um elemento.

## Critérios de aceitação

- [x] Tela para gerenciamento de usuários cadastrados
- [x] Lista de usuários (com filtro)
- [x] Botão para edição (se necessário uma tela para fazer edição)
- [x] Botão para deleção

**Comment by guilherme-puida** [comment]
Versão inicial da tela pronta. Ainda não permite filtragem nem dá mensagem quando a ação finaliza.

**Comment by guilherme-puida** [comment]
Filtro finalizado.
