### ISSUE TITLE
Criar README do Docs

### ISSUE THREAD

**Issue by baraky** [fga-eps-mds/2021-2-SysArq-Doc#55]
## Descrição:
Criar README com informações básicas e importantes sobre o projeto.

## Critérios de aceitação

- [ ] Informações sobre os integrantes
- [ ] Listar os outros 3 repositórios
- [ ] Como rodar o projeto (explicar também como deve ser o .env)
- [ ] Como contribuir (linkar o doc CONTRIBUTING)

**Comment by dartmol203** [comment]
@baraky a gente vai ter um site de documentação para esse semestre já na próxima release major?
