### ISSUE TITLE
[US04/US13] Tela de configurações

### ISSUE THREAD

**Issue by baraky** [fga-eps-mds/2021-2-SysArq-Doc#56]
US04 - Eu, **como** administrador, **quero** cadastrar novos usuários **para** dar acesso a outras pessoas ao sistema.

US13 - Eu, **como** administrador, **quero** gerenciar os usuários cadastrados **para** editar e deletar quando necessário.

## Descrição

Criar tela de configurações. A princípio, a tela será usada para gerenciamento de usuários no sistema, porém está sujeita a incremento futuros.

## Critérios de aceitação

- [ ] Tela de configurações
- [ ] Botão para cadastro de usuários (sem rota)
- [ ] Botão para gerenciamento de usuários (sem rota)

**Comment by dartmol203** [comment]
Boa tarde! fiz um protótipo de baixa fidelidade para ter uma ideia de como ficaria a página de configurações e gostaria de saber se essa base serviria bem para resolver essa issue:
![image](https://user-images.githubusercontent.com/78980992/157304591-07cad19b-833d-445b-a65e-4380c15055e2.png)
se tiver alguma observação, me avise, por favor!

**Comment by baraky** [comment]
Bem legal ter feito o protótipo 

Era mais ou menos dessa forma que eu estava pensando mesmo, com os botões meio que no mesmo padrão de tamanho das outras telas.

**Comment by dartmol203** [comment]
Ótimo, era no tamanho padrão mesmo que estava pensando, vlw!
