### ISSUE TITLE
Rota de criar usuário não é segura

### ISSUE THREAD

**Issue by guilherme-puida** [fga-eps-mds/2021-2-SysArq-Doc#62]
## Descrição

Atualmente, o a rota de criar novos usuários no Profile não faz nenhum tipo de autenticação. Isso permite que qualquer um possa criar um usuário e acessar o sistema.

## Passos para reprodução

1. Fazer uma requisição para /users/register com os campos necessários no corpo (usuário, nome, sobrenome, cpf e senha)

## Comportamento esperado

O sistema deveria requerir autenticação de um Administrador (como é descrito na [US05](https://github.com/fga-eps-mds/2021-2-sysarq-doc/issues/36)) para criar novos usuários.

**Comment by paulomacieltorresfilho** [comment]
Estou pensando em formas de criar o primeiro usuário, para ele ser base para os outros. Pensei em criar uma variável de ambiente com os campos obrigatórios do modelo e depois criar um arquivo .py que cria o usuário (de tipo Administrador). É possível? Existem opções melhores?

Se for viável, queria saber como posso fazer esse arquivo rodar na primeira vez que o `docker-compose up` for acionado.

**Comment by paulomacieltorresfilho** [comment]
![Exemplo de como o env-reference ficaria](https://user-images.githubusercontent.com/75345775/161171537-c5ca263c-754d-46c6-870d-96e0e8395148.png)
Exemplo de como o env-reference
